name: CI/CD Release

env:
  IMAGE_REGISTRY: ${{ secrets.IMAGE_REGISTRY }}/${{ secrets.IMAGE_REGISTRY_USER }}
  IMAGE_REGISTRY_USER: ${{ secrets.IMAGE_REGISTRY_USER }}
  IMAGE_REGISTRY_PASSWORD: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}

  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: "ivan-jimeno-ramirez1-dev"

  # Nombre de la route que quieres exponer (ajusta según tu caso)
  ROUTE_NAME: "helloworld"

  # Si no lo pones tú, tomará el nombre de la carpeta actual (basename) en 'Determine app name'
  APP_NAME: ""

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build
        run: mvn clean install -DskipUTs=true -DskipITs=true
  
  unit-tests-sonar:
    name: Unit tests & Sonar
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run tests
        run: mvn clean test -Pcoverage
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: SonarCloud Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.projectKey=Salle-models-de-desenvolupament_mdas-ci-cd-hello-world -Dsonar.coverage.jacoco.xmlReportPaths=target/jacoco-report/jacoco.xml -DskipTests=true
  
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: unit-tests-sonar
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run tests
        run: mvn clean verify -DskipUTs=true
  
  security:
    name: SNYK (Security)
    runs-on: ubuntu-latest
    needs: integration-tests
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  versioning:
    name: Semantic Release versioning
    permissions:
      contents: write
      issues: write
      pull-requests: write
    needs: [security]
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm clean-install
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Obtain version
        id: get_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export VERSION=$(npx semantic-release --dry-run | grep 'The next release version is' | sed -E 's/.* ([[:digit:].]+)$/\1/')
          if [ -z "$VERSION" ]; then
            echo "Failed to determine version" >&2
            exit 1
          fi
          echo "version=${VERSION}-${GITHUB_SHA::12}" >> $GITHUB_OUTPUT
      - name: Perform release
        id: perform_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      - name: view generated version
        run: echo "version=${{ steps.get_version.outputs.version }}"
  
  artifact:
    name: Artifact
    runs-on: ubuntu-latest
    needs: [versioning]
    outputs:
      version: ${{ needs.versioning.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Build Quarkus application
        run: |
          ./mvnw clean package -DskipTests

      - name: Determine app name
        if: env.APP_NAME == ''
        run: |
          echo "APP_NAME=$(basename $PWD)" | tee -a $GITHUB_ENV

      - name: Build from Dockerfile
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.APP_NAME }}
          tags: ${{ needs.versioning.outputs.version }} latest

          dockerfiles: |
            ./src/main/docker/Dockerfile.jvm

      - name: Push to registry
        id: push-image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.IMAGE_REGISTRY_USER }}
          password: ${{ env.IMAGE_REGISTRY_PASSWORD }}
      
  openshift-ci-cd:
    name: Build and deploy to OpenShift (Blue-Green)
    runs-on: ubuntu-latest
    environment: production
    needs: [artifact]

    # Si quieres exponer ROUTE o SELECTOR como outputs, puedes hacerlo
    # (aquí lo hemos omitido por simplicidad)
    # outputs:
    #   ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
    #   SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}

    steps:
      - name: Check for required secrets
        uses: actions/github-script@v6
        with:
          script: |
            const secrets = {
              OPENSHIFT_SERVER: `${{ secrets.OPENSHIFT_SERVER }}`,
              OPENSHIFT_TOKEN: `${{ secrets.OPENSHIFT_TOKEN }}`,
            };

            const GHCR = "ghcr.io";
            if (`${{ env.IMAGE_REGISTRY }}`.startsWith(GHCR)) {
              core.info(`Image registry is ${GHCR} - no registry password required`);
            }
            else {
              core.info("A registry password is required");
              secrets["IMAGE_REGISTRY_PASSWORD"] = `${{ secrets.IMAGE_REGISTRY_PASSWORD }}`;
            }

            const missingSecrets = Object.entries(secrets).filter(([ name, value ]) => {
              if (value.length === 0) {
                core.error(`Secret "${name}" is not set`);
                return true;
              }
              core.info(`✔️ Secret "${name}" is set`);
              return false;
            });

            if (missingSecrets.length > 0) {
              core.setFailed(`❌ At least one required secret is not set in the repository. \n` +
                "You can add it using:\n" +
                "GitHub UI: https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository \n" +
                "GitHub CLI: https://cli.github.com/manual/gh_secret_set \n" +
                "Also, refer to https://github.com/redhat-actions/oc-login#getting-started-with-the-action-or-see-example");
            }
            else {
              core.info(`✅ All the required secrets are set`);
            }

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Build Quarkus application
        run: |
          ./mvnw clean package -DskipTests

      - name: Determine app name
        if: env.APP_NAME == ''
        run: |
          echo "APP_NAME=$(basename $PWD)" | tee -a $GITHUB_ENV

      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4

      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
          openshift_token: ${{ env.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}

      - name: Blue-Green Deployment
        run: |
          # Comprueba si existe la Route
          # Si no existe, ROUTE_DEST estará vacío; si existe, contendrá "APPNAME-blue" o "APPNAME-green"
          ROUTE_DEST=$(oc get route ${{ env.ROUTE_NAME }} -n ${{ env.OPENSHIFT_NAMESPACE }} \
            -o jsonpath="{.spec.to.name}" --ignore-not-found)

          echo "Route actual: '${ROUTE_DEST}' (vacío si no existe)"

          if [ -z "$ROUTE_DEST" ]; then
            echo "La Route ${{ env.ROUTE_NAME }} NO existe. Creando despliegue inicial en BLUE..."
            # Asegúrate de limpiar lo que pudiera existir en BLUE, por si acaso:
            oc delete deployment,service,route -l app=${{ env.APP_NAME }}-blue \
              -n ${{ env.OPENSHIFT_NAMESPACE }} --ignore-not-found=true

            # Creamos app en BLUE
            oc new-app ${{ env.IMAGE_REGISTRY }}/${{ env.APP_NAME }}:${{ needs.artifact.outputs.version }} \
              --name=${{ env.APP_NAME }}-blue \
              -n ${{ env.OPENSHIFT_NAMESPACE }}

            # Esperamos a que se complete el rollout
            oc rollout status deployment/${{ env.APP_NAME }}-blue -n ${{ env.OPENSHIFT_NAMESPACE }}

            # Exponemos la nueva app con la route $ROUTE_NAME
            oc expose service ${{ env.APP_NAME }}-blue --name=${{ env.ROUTE_NAME }} -n ${{ env.OPENSHIFT_NAMESPACE }}

          else
            if [ "$ROUTE_DEST" = "${{ env.APP_NAME }}-blue" ]; then
              echo "La Route apunta a BLUE. Desplegamos la nueva versión en GREEN."
              # Limpiamos despliegues anteriores en GREEN
              oc delete deployment,service,route -l app=${{ env.APP_NAME }}-green \
                -n ${{ env.OPENSHIFT_NAMESPACE }} --ignore-not-found=true

              # Desplegamos en GREEN
              oc new-app ${{ env.IMAGE_REGISTRY }}/${{ env.APP_NAME }}:${{ needs.artifact.outputs.version }} \
                --name=${{ env.APP_NAME }}-green \
                -n ${{ env.OPENSHIFT_NAMESPACE }}

              # Esperamos a que se complete el rollout
              oc rollout status deployment/${{ env.APP_NAME }}-green -n ${{ env.OPENSHIFT_NAMESPACE }}

              # Actualizamos la route para que apunte a GREEN
              oc patch route/${{ env.ROUTE_NAME }} -n ${{ env.OPENSHIFT_NAMESPACE }} \
                -p "{\"spec\":{\"to\":{\"name\":\"${{ env.APP_NAME }}-green\"}}}"

            else
              echo "La Route apunta a GREEN. Desplegamos la nueva versión en BLUE."
              # Limpiamos despliegues anteriores en BLUE
              oc delete deployment,service,route -l app=${{ env.APP_NAME }}-blue \
                -n ${{ env.OPENSHIFT_NAMESPACE }} --ignore-not-found=true

              # Desplegamos en BLUE
              oc new-app ${{ env.IMAGE_REGISTRY }}/${{ env.APP_NAME }}:${{ needs.artifact.outputs.version }} \
                --name=${{ env.APP_NAME }}-blue \
                -n ${{ env.OPENSHIFT_NAMESPACE }}

              # Esperamos a que se complete el rollout
              oc rollout status deployment/${{ env.APP_NAME }}-blue -n ${{ env.OPENSHIFT_NAMESPACE }}

              # Actualizamos la route para que apunte a BLUE
              oc patch route/${{ env.ROUTE_NAME }} -n ${{ env.OPENSHIFT_NAMESPACE }} \
                -p "{\"spec\":{\"to\":{\"name\":\"${{ env.APP_NAME }}-blue\"}}}"
            fi
          fi