name: CI Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-tests-sonar:
    name: Build - Tests - Sonar (PR)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and tests
        run: |
          mvn clean verify
      - name: Sonar
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
        run: |
          mvn sonar:sonar \
          -Dsonar.qualitygate.wait=true \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/jacoco-report/jacoco.xml \
          -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: target
          path: ./target/*
 
  security:
    name: Security (SNYK) (PR)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:  
          args: 
            --file=pom.xml --severity-threshold=high --fail-on=upgradable
